config/routes.rb
Rails.application.routes.draw do
  resources :avrs

  resources :users

  resources :mmms
 get 'mmms', to: 'mmms#findmms'

end

app/models/avr.rb
class Avr < ActiveRecord::Base
  attr_reader :mdu_tkd, :author_tokens
  has_many :mmms
  has_many :users
  def mmm_tokens ()
    self.mmm_id = id
  end
end

app/models/mmm.rb
class Mmm < ActiveRecord::Base
  belongs_to :avr
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :avr
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/avrs_controller.rb
class AvrsController < ApplicationController
  before_action :set_avr, only: [:show, :edit, :update, :destroy]

  # GET /avrs
  # GET /avrs.json
  def index
    @avrs = Avr.all
  end

  # GET /avrs/1
  # GET /avrs/1.json
  def show
  end

  # GET /avrs/new
  def new
    @avr = Avr.new
  end

  # GET /avrs/1/edit
  def edit
  end

  # POST /avrs
  # POST /avrs.json
  def create
    @avr = Avr.new(avr_params)

    respond_to do |format|
      if @avr.save
        format.html { redirect_to @avr, notice: 'Avr was successfully created.' }
        format.json { render :show, status: :created, location: @avr }
      else
        format.html { render :new }
        format.json { render json: @avr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avrs/1
  # PATCH/PUT /avrs/1.json
  def update
    respond_to do |format|
      if @avr.update(avr_params)
        format.html { redirect_to @avr, notice: 'Avr was successfully updated.' }
        format.json { render :show, status: :ok, location: @avr }
      else
        format.html { render :edit }
        format.json { render json: @avr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avrs/1
  # DELETE /avrs/1.json
  def destroy
    @avr.destroy
    respond_to do |format|
      format.html { redirect_to avrs_url, notice: 'Avr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avr
      @avr = Avr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avr_params
      params.require(:avr).permit(:mmm_id, :type_avr, :material, :comment, :user_id, :date_on, :date_off)
    end
end

app/controllers/mmms_controller.rb
class MmmsController < ApplicationController
  before_action :set_mmm, only: [:show, :edit, :update, :destroy]

  # GET /mmms
  # GET /mmms.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: MmmsDatatable.new(view_context) }
    end
  end
  def findmmms
    @mmms = Mmm.where("mdu_tkd like ?", "%#{params[:q]}%")
    render :json => @mmms
  end

  # GET /mmms/1
  # GET /mmms/1.json
  def show
  end

  # GET /mmms/new
  def new
    @mmm = Mmm.new
  end

  # GET /mmms/1/edit
  def edit
  end

  # POST /mmms
  # POST /mmms.json
  def create
    @mmm = Mmm.new(mmm_params)

    respond_to do |format|
      if @mmm.save
        format.html { redirect_to @mmm, notice: 'Mmm was successfully created.' }
        format.json { render :show, status: :created, location: @mmm }
      else
        format.html { render :new }
        format.json { render json: @mmm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mmms/1
  # PATCH/PUT /mmms/1.json
  def update
    respond_to do |format|
      if @mmm.update(mmm_params)
        format.html { redirect_to @mmm, notice: 'Mmm was successfully updated.' }
        format.json { render :show, status: :ok, location: @mmm }
      else
        format.html { render :edit }
        format.json { render json: @mmm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mmms/1
  # DELETE /mmms/1.json
  def destroy
    @mmm.destroy
    respond_to do |format|
      format.html { redirect_to mmms_url, notice: 'Mmm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mmm
      @mmm = Mmm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mmm_params
      params.require(:mmm).permit(:mdu_tkd, :adress, :porch, :ip, :sys_name, :ingress, :mod)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avrs_helper.rb
module AvrsHelper
end

app/helpers/mmms_helper.rb
module MmmsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/avrs/_form.html.erb
<%= form_for(@avr) do |f| %>
  <% if @avr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avr.errors.count, "error") %> prohibited this avr from being saved:</h2>

      <ul>
      <% @avr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mmm_tokens, "Mmm" %><br />
    <%= f.text_field :mmm_tokens, "data-pre" => @avr.mmms.map(&:attributes).to_json %>
  </div>
  <div class="field">
    <%= f.label :type_avr %><br>
    <%= f.text_field :type_avr %>
  </div>
  <div class="field">
    <%= f.label :material %><br>
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :date_on %><br>
    <%= f.datetime_select :date_on %>
  </div>
  <div class="field">
    <%= f.label :date_off %><br>
    <%= f.datetime_select :date_off %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avrs/edit.html.erb
<h1>Editing avr</h1>

<%= render 'form' %>

<%= link_to 'Show', @avr %> |
<%= link_to 'Back', avrs_path %>

app/views/avrs/index.html.erb
<h1>Listing avrs</h1>

<table>
  <thead>
    <tr>
      <th>Mmm</th>
      <th>Type avr</th>
      <th>Material</th>
      <th>Comment</th>
      <th>User</th>
      <th>Date on</th>
      <th>Date off</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avrs.each do |avr| %>
      <tr>
        <td><%= avr.mmm_id %></td>
        <td><%= avr.type_avr %></td>
        <td><%= avr.material %></td>
        <td><%= avr.comment %></td>
        <td><%= avr.user_id %></td>
        <td><%= avr.date_on %></td>
        <td><%= avr.date_off %></td>
        <td><%= link_to 'Show', avr %></td>
        <td><%= link_to 'Edit', edit_avr_path(avr) %></td>
        <td><%= link_to 'Destroy', avr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avr', new_avr_path %>

app/views/avrs/new.html.erb
<h1>New avr</h1>

<%= render 'form' %>

<%= link_to 'Back', avrs_path %>

app/views/avrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mmm:</strong>
  <%= @avr.mmm_id %>
</p>

<p>
  <strong>Type avr:</strong>
  <%= @avr.type_avr %>
</p>

<p>
  <strong>Material:</strong>
  <%= @avr.material %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @avr.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @avr.user_id %>
</p>

<p>
  <strong>Date on:</strong>
  <%= @avr.date_on %>
</p>

<p>
  <strong>Date off:</strong>
  <%= @avr.date_off %>
</p>

<%= link_to 'Edit', edit_avr_path(@avr) %> |
<%= link_to 'Back', avrs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Untitled7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "application", "token-input-facebook" %>
  <%= javascript_include_tag :defaults, "jquery.tokeninput" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mmms/_form.html.erb
<%= form_for(@mmm) do |f| %>
  <% if @mmm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mmm.errors.count, "error") %> prohibited this mmm from being saved:</h2>

      <ul>
      <% @mmm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mdu_tkd %><br>
    <%= f.text_field :mdu_tkd %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :porch %><br>
    <%= f.text_field :porch %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :sys_name %><br>
    <%= f.text_field :sys_name %>
  </div>
  <div class="field">
    <%= f.label :ingress %><br>
    <%= f.text_field :ingress %>
  </div>
  <div class="field">
    <%= f.label :mod %><br>
    <%= f.check_box :mod %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mmms/edit.html.erb
<h1>Editing mmm</h1>

<%= render 'form' %>

<%= link_to 'Show', @mmm %> |
<%= link_to 'Back', mmms_path %>

app/views/mmms/index.html.erb
<h1>Listing mmms</h1>

<table id="mmms" class="display" data-source="<%= mmms_url(format: "json") %>">
  <thead>
    <tr>
      <th>Mdu tkd</th>
      <th>Adress</th>
      <th>Porch</th>
      <th>Ip</th>
      <th>Sys name</th>
      <th>Ingress</th>
      <th>Mod</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  </tbody>
</table>

<br>

<%= link_to 'New Mmm', new_mmm_path %>

app/views/mmms/new.html.erb
<h1>New mmm</h1>

<%= render 'form' %>

<%= link_to 'Back', mmms_path %>

app/views/mmms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mdu tkd:</strong>
  <%= @mmm.mdu_tkd %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @mmm.adress %>
</p>

<p>
  <strong>Porch:</strong>
  <%= @mmm.porch %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @mmm.ip %>
</p>

<p>
  <strong>Sys name:</strong>
  <%= @mmm.sys_name %>
</p>

<p>
  <strong>Ingress:</strong>
  <%= @mmm.ingress %>
</p>

<p>
  <strong>Mod:</strong>
  <%= @mmm.mod %>
</p>

<%= link_to 'Edit', edit_mmm_path(@mmm) %> |
<%= link_to 'Back', mmms_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>